---
- name: Check current docker-compose version
  command: '{{ docker_compose.path }} --version'
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if different
  file:
    path: '{{ docker_compose.path }}'
    state: absent
  when:
    - docker_compose_current_version.stdout is defined
    - docker_compose.version not in docker_compose_current_version.stdout

- name: Install Docker Compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
    dest: '{{ docker_compose.path }}'
    mode: 0755
    timeout: '120'
    validate_certs: 'no'
  when:
    - docker_compose_current_version.rc == 2 or docker_compose.version not in docker_compose_current_version.stdout
  ignore_errors: true