---
- name: Ensure Docker prometheus metrics firewall port is allow
  firewalld:
    port: '{{ item }}'
    permanent: 'true'
    state: 'enabled'
  with_items:
    - '{{ docker_metrics_port }}/tcp'
  when:
    - ansible_distribution_major_version|int > 6
  register: firewall_update

- name: Reload firewalld service
  service:
    name: firewalld
    state: reloaded
  when:
    - firewall_update|changed
    - ansible_distribution_major_version|int > 6