---
- name: Ensure Docker prometheus metrics firewall port is allow
  firewalld:
    port: '{{ item }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  with_items: '{{ docker_port.metrics_port }}'
