---
- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Create docker image directory
  file:
    path: '{{ docker_path }}/docker'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0711'

- name: Docker configureation
  template:
    owner: 'root'
    group: 'root'
    mode: '0644'
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'daemon.json', dest: '/etc/docker/' }
  register: conf_update

- name: Configure kernel parameters
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  loop: '{{ docker_kernel_parameters }}'

- name: Configure proxy variables
  lineinfile:
    dest: '/lib/systemd/system/docker.service'
    state: 'present'
    insertafter: '\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^Environment="HTTP_PROXY',  line: 'Environment="HTTP_PROXY={{ docker_proxy_server }}/"' }
    - { regexp: '^Environment="HTTPS_PROXY', line: 'Environment="HTTPS_PROXY={{ docker_proxy_server }}/"' }
    - { regexp: '^Environment="NO_PROXY',    line: 'Environment="NO_PROXY=localhost,{{ docker_noproxy_address | list | join(",") }}"' }
  register: proxy_update
  when: docker_proxy_server is defined

- name: Configure proxy variables
  lineinfile:
    dest: '/lib/systemd/system/docker.service'
    state: 'absent'
    regexp: '{{ item.regexp }}'
  loop:
    - { regexp: '^Environment="HTTP_PROXY' }
    - { regexp: '^Environment="HTTPS_PROXY' }
    - { regexp: '^Environment="NO_PROXY' }
  register: noproxy_update
  when: docker_proxy_server is not defined

- name: Reload the Docker service
  shell: echo ''
  notify: 'Reloading the Docker service'
  when: conf_update is changed or soft_update is changed or proxy_update is changed or noproxy_update is changed

- name: Docker maintenance task 
  include: 'maintenance.yml'

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Install Docker compose
  include: 'compose.yml'
  when: docker_compose.install | bool

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    -  consul_public_register | bool
