---
- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Include firewall tasks
  include: 'firewall.yml'

- name: Create docker image directory
  file:
    path: '{{ docker_path }}/docker'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: 0711

- name: Docker configureation
  template:
    owner: root
    group: root
    mode: 0644
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'daemon.json', dest: '/etc/docker/' }
  register: conf_update

- name: Configure kernel parameters
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/20-sysctl.conf
  with_items:
    - '{{ docker_kernel_parameters }}'

- name: Reload the Docker service
  shell: echo ''
  notify: 'Reloading the Docker service'
  when: conf_update is changed or soft_update is changed

- name: Docker maintenance task 
  include: 'maintenance.yml'

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Install Docker compose
  include: 'compose.yml'
  when: docker_compose.install

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when: consul_public_register
