---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Ensure old versions of Docker are not installed
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker YUM repositories
  yum_repository:
    name: '{{ docker_repo_name }}'
    description: '{{ docker_repo_name }} repo'
    file: '{{ docker_repo_name }}'
    baseurl: '{{ docker_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Docker packages
  yum:
    name: '{{ docker_package }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_update
