---
- name: Ensure old versions of Docker are not installed
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker YUM repositories
  yum_repository:
    name: '{{ docker_repo_name }}'
    description: '{{ docker_repo_name }} repo'
    file: '{{ docker_repo_name }}'
    baseurl: '{{ docker_repo_url }}'
    gpgcheck: no

- name: Install the Docker packages
  yum:
    name: '{{ docker_package }}'
    state: '{{ docker_package_state }}'