---
- name: Set docker_selinux to false for default
  set_fact:
    docker_selinux: '{{ false }}'

- name: Get getenforce binary
  stat:
    path: '/usr/sbin/getenforce'
  register: getenforce_bin
  become: yes

- name: Collect getenforce output
  command: getenforce
  register: sestatus
  when: 'getenforce_bin.stat.exists'
  changed_when: false
  become: yes

- name: Set docker_selinux to true if getenforce returns Enforcing or Permissive
  set_fact:
    docker_selinux: '{{ true }}'
  when: 'getenforce_bin.stat.exists and ("Enforcing" in sestatus.stdout or "Permissive" in sestatus.stdout)'

- name: Allow php-fpm to listen on service port
  seport:
    ports: '{{ docker_port.metrics_port }}'
    proto: 'tcp'
    setype: 'http_port_t'
    state: 'present'
  when:
    - docker_selinux | bool